joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'left_wheel'
  right_wheel: 'right_wheel'
  publish_rate: 50.0
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

base_frame_id: base_footprint
  


